# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitbill', '0008_auto_20161225_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='raw',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='splitbill.RawTransaction'),
            preserve_default=False,
        ),
    ]
