# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitbill', '0009_transaction_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='statement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='splitbill.Statement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='statement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='splitbill.Statement'),
            preserve_default=False,
        ),
    ]
