# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitbill', '0011_auto_20161226_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='splitbill.Account'),
            preserve_default=False,
        ),
    ]
